// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountAllUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, userUuid uuid.UUID) (int64, error)
	GetAllUserCreateASC(ctx context.Context, arg GetAllUserCreateASCParams) ([]User, error)
	GetAllUserCreateDESC(ctx context.Context, arg GetAllUserCreateDESCParams) ([]User, error)
	GetAllUserIdASC(ctx context.Context, arg GetAllUserIdASCParams) ([]User, error)
	GetAllUserIdDESC(ctx context.Context, arg GetAllUserIdDESCParams) ([]User, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	GetUserByUUID(ctx context.Context, userUuid uuid.UUID) (User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (int64, error)
	TrashUser(ctx context.Context, userUuid uuid.UUID) (int64, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
