// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_email,
    user_password,
    user_name,
    user_age,
    user_status,
    user_role
) VALUES (
     $1, $2, $3, $4, $5, $6
 ) RETURNING user_id, user_uuid, user_email, user_password, user_name, user_age, user_status, user_role, user_deleted_at, user_created_at, user_updated_at
`

type CreateUserParams struct {
	UserEmail    string `json:"user_email"`
	UserPassword string `json:"user_password"`
	UserName     string `json:"user_name"`
	UserAge      *int32 `json:"user_age"`
	UserStatus   int32  `json:"user_status"`
	UserRole     int32  `json:"user_role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserEmail,
		arg.UserPassword,
		arg.UserName,
		arg.UserAge,
		arg.UserStatus,
		arg.UserRole,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserName,
		&i.UserAge,
		&i.UserStatus,
		&i.UserRole,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
UPDATE users
SET user_deleted_at = NOW()
WHERE user_uuid = $1
AND user_deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT user_id, user_uuid, user_email, user_password, user_name, user_age, user_status, user_role, user_deleted_at, user_created_at, user_updated_at FROM users WHERE user_deleted_at IS NULL
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.UserUuid,
			&i.UserEmail,
			&i.UserPassword,
			&i.UserName,
			&i.UserAge,
			&i.UserStatus,
			&i.UserRole,
			&i.UserDeletedAt,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :execrows
UPDATE users
SET user_deleted_at = NULL
WHERE user_uuid = $1
AND user_deleted_at IS NOT NULL
`

func (q *Queries) RestoreUser(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreUser, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const trashUser = `-- name: TrashUser :execrows
DELETE
FROM users
WHERE user_uuid = $1
AND user_deleted_at IS NOT NULL
`

func (q *Queries) TrashUser(ctx context.Context, userUuid uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, trashUser, userUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    user_name = COALESCE($2,user_name),
    user_password = COALESCE($3,user_password),
    user_age = COALESCE($4,user_age),
    user_status = COALESCE($5,user_status),
    user_role = COALESCE($6,user_role)
WHERE
    user_uuid = $1 AND
    user_deleted_at IS NULL
    RETURNING user_id, user_uuid, user_email, user_password, user_name, user_age, user_status, user_role, user_deleted_at, user_created_at, user_updated_at
`

type UpdateUserParams struct {
	UserUuid     uuid.UUID `json:"user_uuid"`
	UserName     *string   `json:"user_name"`
	UserPassword *string   `json:"user_password"`
	UserAge      *int32    `json:"user_age"`
	UserStatus   *int32    `json:"user_status"`
	UserRole     *int32    `json:"user_role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserUuid,
		arg.UserName,
		arg.UserPassword,
		arg.UserAge,
		arg.UserStatus,
		arg.UserRole,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUuid,
		&i.UserEmail,
		&i.UserPassword,
		&i.UserName,
		&i.UserAge,
		&i.UserStatus,
		&i.UserRole,
		&i.UserDeletedAt,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}
