CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- create users table
CREATE TABLE IF NOT EXISTS users(
    user_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid       UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    user_email      VARCHAR(150) NOT NULL UNIQUE,
    user_password   VARCHAR(90) NOT NULL,
    user_name       VARCHAR(255) NOT NULL,
    user_age        INT CHECK( user_age >= 18 AND user_age <= 100),
    user_role       INT NOT NULL DEFAULT 1 CHECK (user_role IN (1, 3)),
    user_status     INT NOT NULL DEFAULT 1 CHECK (user_status IN (1, 3)),
    user_deleted_at TIMESTAMPTZ DEFAULT NULL,
    user_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- create comment table
COMMENT ON COLUMN users.user_age IS 'users age, must be between 18 and 100';
COMMENT ON COLUMN users.user_role IS 'user role, 1 - admin, 2 - user, 3 - deleted';
COMMENT ON COLUMN users.user_status IS 'user status, 1 - active, 2 - blocked, 3 - deleted';
COMMENT ON COLUMN users.user_deleted_at IS 'date of deletion';

-- create index table
CREATE INDEX IF NOT EXISTS idx_user_user_role ON users(user_role);
CREATE INDEX IF NOT EXISTS idx_user_user_status ON users(user_status);
CREATE INDEX IF NOT EXISTS idx_user_user_created_at ON users(user_created_at);
CREATE INDEX IF NOT EXISTS idx_user_user_deleted_at ON users(user_deleted_at);
CREATE INDEX IF NOT EXISTS idx_user_user_email_status ON users(user_email,user_status);

-- create function
CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.user_updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_user_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_user_updated_at();